# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ngn_fba_ai_proto import ai_pb2 as ngn__fba__ai__proto_dot_ai__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ngn_fba_ai_proto/ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OcrServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.unary_unary(
                '/ngn.fba.ai.v1.OcrService/Recognize',
                request_serializer=ngn__fba__ai__proto_dot_ai__pb2.ImageRequest.SerializeToString,
                response_deserializer=ngn__fba__ai__proto_dot_ai__pb2.OcrResult.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ngn.fba.ai.v1.OcrService/Health',
                request_serializer=ngn__fba__ai__proto_dot_ai__pb2.Empty.SerializeToString,
                response_deserializer=ngn__fba__ai__proto_dot_ai__pb2.HealthResponse.FromString,
                _registered_method=True)


class OcrServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Recognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OcrServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=ngn__fba__ai__proto_dot_ai__pb2.ImageRequest.FromString,
                    response_serializer=ngn__fba__ai__proto_dot_ai__pb2.OcrResult.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ngn__fba__ai__proto_dot_ai__pb2.Empty.FromString,
                    response_serializer=ngn__fba__ai__proto_dot_ai__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ngn.fba.ai.v1.OcrService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ngn.fba.ai.v1.OcrService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OcrService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ngn.fba.ai.v1.OcrService/Recognize',
            ngn__fba__ai__proto_dot_ai__pb2.ImageRequest.SerializeToString,
            ngn__fba__ai__proto_dot_ai__pb2.OcrResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ngn.fba.ai.v1.OcrService/Health',
            ngn__fba__ai__proto_dot_ai__pb2.Empty.SerializeToString,
            ngn__fba__ai__proto_dot_ai__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LayoutServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/ngn.fba.ai.v1.LayoutService/Predict',
                request_serializer=ngn__fba__ai__proto_dot_ai__pb2.OcrResult.SerializeToString,
                response_deserializer=ngn__fba__ai__proto_dot_ai__pb2.LayoutResult.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ngn.fba.ai.v1.LayoutService/Health',
                request_serializer=ngn__fba__ai__proto_dot_ai__pb2.Empty.SerializeToString,
                response_deserializer=ngn__fba__ai__proto_dot_ai__pb2.HealthResponse.FromString,
                _registered_method=True)


class LayoutServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LayoutServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=ngn__fba__ai__proto_dot_ai__pb2.OcrResult.FromString,
                    response_serializer=ngn__fba__ai__proto_dot_ai__pb2.LayoutResult.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ngn__fba__ai__proto_dot_ai__pb2.Empty.FromString,
                    response_serializer=ngn__fba__ai__proto_dot_ai__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ngn.fba.ai.v1.LayoutService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ngn.fba.ai.v1.LayoutService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LayoutService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ngn.fba.ai.v1.LayoutService/Predict',
            ngn__fba__ai__proto_dot_ai__pb2.OcrResult.SerializeToString,
            ngn__fba__ai__proto_dot_ai__pb2.LayoutResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ngn.fba.ai.v1.LayoutService/Health',
            ngn__fba__ai__proto_dot_ai__pb2.Empty.SerializeToString,
            ngn__fba__ai__proto_dot_ai__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CleanServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Clean = channel.unary_unary(
                '/ngn.fba.ai.v1.CleanService/Clean',
                request_serializer=ngn__fba__ai__proto_dot_ai__pb2.CleanRequest.SerializeToString,
                response_deserializer=ngn__fba__ai__proto_dot_ai__pb2.CleanResult.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ngn.fba.ai.v1.CleanService/Health',
                request_serializer=ngn__fba__ai__proto_dot_ai__pb2.Empty.SerializeToString,
                response_deserializer=ngn__fba__ai__proto_dot_ai__pb2.HealthResponse.FromString,
                _registered_method=True)


class CleanServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Clean(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CleanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Clean': grpc.unary_unary_rpc_method_handler(
                    servicer.Clean,
                    request_deserializer=ngn__fba__ai__proto_dot_ai__pb2.CleanRequest.FromString,
                    response_serializer=ngn__fba__ai__proto_dot_ai__pb2.CleanResult.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ngn__fba__ai__proto_dot_ai__pb2.Empty.FromString,
                    response_serializer=ngn__fba__ai__proto_dot_ai__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ngn.fba.ai.v1.CleanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ngn.fba.ai.v1.CleanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CleanService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Clean(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ngn.fba.ai.v1.CleanService/Clean',
            ngn__fba__ai__proto_dot_ai__pb2.CleanRequest.SerializeToString,
            ngn__fba__ai__proto_dot_ai__pb2.CleanResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ngn.fba.ai.v1.CleanService/Health',
            ngn__fba__ai__proto_dot_ai__pb2.Empty.SerializeToString,
            ngn__fba__ai__proto_dot_ai__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
