# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ngn_fba_ai_proto/ai.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ngn_fba_ai_proto/ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ngn_fba_ai_proto/ai.proto\x12\rngn.fba.ai.v1\"\x07\n\x05\x45mpty\"\x1f\n\x0eHealthResponse\x12\r\n\x05model\x18\x01 \x01(\t\"C\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x16\n\tunwarping\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\x0c\n\n_unwarping\"E\n\tOcrResult\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x10\n\x08ocr_json\x18\x02 \x01(\x0c\x12\x17\n\x0f\x65lapsed_seconds\x18\x03 \x01(\x01\":\n\x0cLayoutResult\x12\x13\n\x0bresult_json\x18\x01 \x01(\x0c\x12\x15\n\rvisualization\x18\x02 \x01(\x0c\"\x89\x01\n\x0c\x43leanRequest\x12.\n\x04kind\x18\x01 \x01(\x0e\x32 .ngn.fba.ai.v1.CleanRequest.Kind\x12\r\n\x05texts\x18\x02 \x03(\t\":\n\x04Kind\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\t\n\x05TRACK\x10\x01\x12\x07\n\x03SKU\x10\x02\x12\r\n\tRECIPIENT\x10\x03\"\x1c\n\x0b\x43leanResult\x12\r\n\x05texts\x18\x01 \x03(\t2\x8f\x01\n\nOcrService\x12\x42\n\tRecognize\x12\x1b.ngn.fba.ai.v1.ImageRequest\x1a\x18.ngn.fba.ai.v1.OcrResult\x12=\n\x06Health\x12\x14.ngn.fba.ai.v1.Empty\x1a\x1d.ngn.fba.ai.v1.HealthResponse2\x90\x01\n\rLayoutService\x12@\n\x07Predict\x12\x18.ngn.fba.ai.v1.OcrResult\x1a\x1b.ngn.fba.ai.v1.LayoutResult\x12=\n\x06Health\x12\x14.ngn.fba.ai.v1.Empty\x1a\x1d.ngn.fba.ai.v1.HealthResponse2\x8f\x01\n\x0c\x43leanService\x12@\n\x05\x43lean\x12\x1b.ngn.fba.ai.v1.CleanRequest\x1a\x1a.ngn.fba.ai.v1.CleanResult\x12=\n\x06Health\x12\x14.ngn.fba.ai.v1.Empty\x1a\x1d.ngn.fba.ai.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ngn_fba_ai_proto.ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=44
  _globals['_EMPTY']._serialized_end=51
  _globals['_HEALTHRESPONSE']._serialized_start=53
  _globals['_HEALTHRESPONSE']._serialized_end=84
  _globals['_IMAGEREQUEST']._serialized_start=86
  _globals['_IMAGEREQUEST']._serialized_end=153
  _globals['_OCRRESULT']._serialized_start=155
  _globals['_OCRRESULT']._serialized_end=224
  _globals['_LAYOUTRESULT']._serialized_start=226
  _globals['_LAYOUTRESULT']._serialized_end=284
  _globals['_CLEANREQUEST']._serialized_start=287
  _globals['_CLEANREQUEST']._serialized_end=424
  _globals['_CLEANREQUEST_KIND']._serialized_start=366
  _globals['_CLEANREQUEST_KIND']._serialized_end=424
  _globals['_CLEANRESULT']._serialized_start=426
  _globals['_CLEANRESULT']._serialized_end=454
  _globals['_OCRSERVICE']._serialized_start=457
  _globals['_OCRSERVICE']._serialized_end=600
  _globals['_LAYOUTSERVICE']._serialized_start=603
  _globals['_LAYOUTSERVICE']._serialized_end=747
  _globals['_CLEANSERVICE']._serialized_start=750
  _globals['_CLEANSERVICE']._serialized_end=893
# @@protoc_insertion_point(module_scope)
